### ISSUE TITLE
decrypt

### ISSUE THREAD

**Issue by babnik63** [p-j/meteor-crypto-sha256#3]
how can we decrypt an encrypted string?

**Comment by p-j** [comment]
You can't. I invite you to read about it on Wikipedia : http://en.wikipedia.org/wiki/SHA-2

SHA256, like SHA1 or MD5 are hashing algorithm, they are one way only.

If you want a two way algorithm, I invite you to check [crypto-aes](https://github.com/p-j/meteor-crypto-aes).
